name: Build Droply

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build app
      run: |
        pyinstaller --onefile --windowed \
        --add-data "gui:gui" \
        --add-data "static:static" \
        --add-data "templates:templates" \
        main.py

    - name: Rename output
      run: |
        mkdir output
        if [ "$RUNNER_OS" == "Windows" ]; then
          mv dist/main.exe output/Droply.exe
        elif [ "$RUNNER_OS" == "macOS" ]; then
          mv dist/main output/Droply
        else
          mv dist/main output/Droply
        fi
      shell: bash

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: Droply-${{ runner.os }}
        path: output/
